DROP TYPE IF EXISTS grocery CASCADE;

CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

DROP TABLE IF EXISTS shopping_list_test;

CREATE TABLE IF NOT EXISTS shopping_list_test (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12, 2) NOT NULL,
    category grocery NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL
)